### ISSUE TITLE
The release-note-issue is unexpectedly updated on PR is closed without merging.

### ISSUE THREAD

**Issue by mazamachi** [kouki-dan/git-issue-release#68]
## Problem
When a PR is closed without merge, `pr.closed` event is triggered, and then the issue is updated unexpectedly.

[![Image from Gyazo](https://i.gyazo.com/a9af5239ce18f272944271b2cce52c9c.png)](https://gyazo.com/a9af5239ce18f272944271b2cce52c9c)

## Solution 
Subscribing `push` events to `main` branch will resolve this problem instantly.
```yaml
on:
  push:
    branches:
      - main
```

(However, [README](https://github.com/kouki-dan/git-issue-release#example-usage) suggests subscribing `close` events. This may be confusing, in my opinion. 🤔 )

**Comment by kouki-dan** [comment]
I use the `pull_request` trigger because I want to run this action only PR is merging. (it affect only a body of an issue)

I read the documentation again, and it indicates to use the `pr.close` event which has a true of `merged` property.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges

I forgot to check this property. So this bug may occur in my opinion.

By the way, it's looking good to use the `push` event instead of the `pull_request` event! I would like to rewrite the README to use the `push` event!

It's not related to this issue, but I was suffering from [this error](https://github.com/kouki-dan/git-issue-release/runs/5474313292?check_suite_focus=true). I think using the `push` event will resolve this error.

Thank you for reporting the issue!
